name: Single Nod Test (NPU)

on:
  pull_request:
    branches:
      - testcases
    paths:
      - ".github/workflows/single-test.yml"
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref (branch, tag, or SHA) to test. If not provided, uses the default branch.'
        required: false
        type: string
        default: ''
      job_filter:
        description: 'Select which job to run (leave empty or "all" to run all jobs)'
        required: false
        type: string
        default: 'all'
      image_a3:
        description: 'The a3 running docker image of the test task.'
        required: false
        type: string
        default: ''
      skip_install_flag:
        description: 'Indicates whether to skip the installation of sglang, defaulting to false.'
        required: false
        type: string
        default: ''
      test_scope:
        description: 'Test scope: all / single / multi'
        required: true
        type: choice
        options:
          - all
          - single
          - multi
        default: 'single'

concurrency:
  group: single-test-npu-${{ inputs.ref || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'workflow_call' }}

jobs:
  set-image-config:
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ steps.set-vars.outputs.ref }}
      job_filter: ${{ steps.set-vars.outputs.job_filter }}
      image_a3: ${{ steps.set-vars.outputs.image_a3 }}
      skip_install_flag: ${{ steps.set-vars.outputs.skip_install_flag }}
      test_scope: ${{ steps.set-vars.outputs.test_scope }}
    steps:
      - name: Set image config
        id: set-vars
        run: |
          if [ -z "${{ inputs.ref }}" ]; then
            echo "ref=" >> $GITHUB_OUTPUT
          else
            echo "ref=${{ inputs.ref }}" >> $GITHUB_OUTPUT
          fi

          if [ -z "${{ inputs.job_filter }}" ]; then
            echo "job_filter=all" >> $GITHUB_OUTPUT
          else
            echo "job_filter=${{ inputs.job_filter }}" >> $GITHUB_OUTPUT
          fi

          if [ -z "${{ inputs.image_a3 }}" ]; then
            echo "image_a3=swr.cn-southwest-2.myhuaweicloud.com/base_image/dockerhub/lmsysorg/sglang:cann9.0.0-a3-B100" >> $GITHUB_OUTPUT
          else
            echo "image_a3=${{ inputs.image_a3 }}" >> $GITHUB_OUTPUT
          fi

          if [ -z "${{ inputs.skip_install_flag }}" ]; then
            echo "skip_install_flag=false" >> $GITHUB_OUTPUT
          else
            echo "skip_install_flag=${{ inputs.skip_install_flag }}" >> $GITHUB_OUTPUT
          fi

          if [ -z "${{ inputs.test_scope }}" ]; then
            echo "test_scope=all" >> $GITHUB_OUTPUT
          else
            echo "test_scope=${{ inputs.test_scope }}" >> $GITHUB_OUTPUT
          fi

  single-node-tests:
    name: single-node-poc
    needs: [ set-image-config ]
    if: ${{ !cancelled() && (needs.set-image-config.outputs.test_scope == 'all' || needs.set-image-config.outputs.test_scope == 'poc') }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        test_config:
#          - name: test_npu_llada2_0_flash
#            runner: linux-aarch64-a3-8
#            test_case: test/registered/ascend/dlm_models/test_npu_llada2_0_flash.py
#            test_type: 'function'
#          - name: test_npu_sdar_8b_chat
#            runner: linux-aarch64-a3-2
#            test_case: test/registered/ascend/dlm_models/test_npu_sdar_8b_chat.py
#            test_type: 'function'
#          - name: test_npu_sdar_30b_a3b_chat
#            runner: linux-aarch64-a3-2
#            test_case: test/registered/ascend/dlm_models/test_npu_sdar_30b_a3b_chat.py
#            test_type: 'function'
#          - name: test_npu_gpt_j_6b
#            runner: linux-aarch64-a3-2
#            test_case: test/registered/ascend/llm_models/test_npu_gpt_j_6b.py
#            test_type: 'function'
#          - name: test_npu_kimi_liner_48b_a3b_instruct
#            runner: linux-aarch64-a3-2
#            test_case: test/registered/ascend/llm_models/test_npu_kimi_liner_48b_a3b_instruct.py
#            test_type: 'function'
#          - name: test_npu_orion_14b_base
#            runner: linux-aarch64-a3-2
#            test_case: test/registered/ascend/llm_models/test_npu_orion_14b_base.py
#            test_type: 'function'
          - name: test_npu_tele_flm
            runner: linux-aarch64-a3-2
            test_case: test/registered/ascend/llm_models/test_npu_tele_flm.py
            test_type: 'function'
#          - name: test_npu_ernie_4_5_vl_28b_a3b_pt
#            runner: linux-aarch64-a3-4
#            test_case: test/registered/ascend/vlm_models/test_npu_ernie_4_5_vl_28b_a3b_pt.py
#            test_type: 'function'
#          - name: test_npu_step3_vl_10b
#            runner: linux-aarch64-a3-4
#            test_case: test/registered/ascend/vlm_models/test_npu_step3_vl_10b.py
#            test_type: 'function'
    uses: ./.github/workflows/nightly-test-npu-e2e-single-node.yml
    with:
      runner: ${{ matrix.test_config.runner }}
      test_type: ${{ matrix.test_config.test_type }}
      test_config_name: ${{ matrix.test_config.name }}
      test_case: ${{ matrix.test_config.test_case }}
      image: swr.cn-southwest-2.myhuaweicloud.com/base_image/dockerhub/lmsysorg/sglang:cann9.0.0-a3-B100
      install_sglang_from_source: false
      transformers_version: ''

  check-all-jobs:
    needs:
      - set-image-config
      - single-node-tests
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Check job status
        run: |
          FAILED=0
          echo "=== Check non-skipped jobs ==="
          ${{ contains(needs.*.result, 'failure') }} && FAILED=1
          ${{ contains(needs.*.result, 'cancelled') }} && FAILED=1
          if [ $FAILED -eq 1 ]; then
            echo "❌ Some jobs failed or cancelled"
            exit 1
          fi
          echo "✅ All selected scope jobs passed"
